### ISSUE TITLE
Q: Migrate to gradle for Android

### ISSUE THREAD

**Issue by oantajames** [decebals/licensius#3]
Hi! I really appreciate the work you have done on this project. Awsome work! 

I m trying to migrate the project from Maven to Gradle, to be able to use it for an Android project.
In the License Generator class in the sign method you do the following : 
 `String encoded = DatatypeConverter.printBase64Binary(signature);`
In android there is no support for DatatypeConverter. So I finally used what android provides on this  ( https://developer.android.com/reference/android/util/Base64.html#encodeToString(byte[],%20int,%20int,%20int) ) 
and it resulted the following : 
` String encoded = Base64.encodeToString(signature, Base64.DEFAULT);`
Doing so every time I run the LicenseTool class I get thrown an Exception(that the licenses is not valid) at the above line.

Could you please give me a hint regarding on how to achieve this ? 

Thanks in advance! 
James

**Comment by decebals** [comment]
I see that I have a [TODO](https://github.com/decebals/licensius/blob/12349d9dafbda6938e87108427094fcaa9700d27/src/main/java/ro/fortsoft/licensius/LicenseGenerator.java#L80) on the lines that use `DatatypeConverter`.
I think that I can fix these TODOs very simple if we switch to Java 8.
What do you think about this move from Java 7 to Java 8?

**Comment by oantajames** [comment]
Already did that.
Will look into it a bit more and if I find a solution I will come back.  Thanks!

**Comment by decebals** [comment]
@oantajames Did you find a solution? Can I close the issue?

**Comment by decebals** [comment]
I closed it because I didn't a response. Please free to open it again if you need help.
